version: "3"

services:
  # Serviço que irá rodar o node
  backend:
    # Imagem base do container
    build: ./back-end 
    # Nome do container para facilitar execução
    container_name: backend
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    # Restarta a imagem caso algo a faça parar
    restart: always
    # Diretório padrão de execução
    working_dir: /app
    volumes:
      # Monta o diretório atual, com todos os dados do projeto, 
      # dentro do diretório /app
      - ./back-end:/app
    # Lista de serviços do qual este serviço depende
    depends_on:
      # Precisa do banco funcionando antes de subir o node
      - db
    # Lista de portas mapeadas de dentro para fora do container
    # na notação porta_de_fora:porta_de_dentro
    ports:
      # Expõe a porta padrão da aplicação: altere aqui caso use outra porta
      - 3001:3001
    # Configura as variáveis de ambiente dentro do container
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      JWT_SECRET: secret
      MYSQL_DB_NAME: delivery-app
      EVAL_ALWAYS_RESTORE_DEV_DB: true
      NODE_ENV: development

  frontend:
    # Imagem base do container
    build: ./front-end 
    # Nome do container para facilitar execução
    container_name: frontend
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    # Restarta a imagem caso algo a faça parar
    restart: always
    # Diretório padrão de execução
    working_dir: /app
    # Lista de volumes (diretórios) mapeados de fora para dentro do container
    volumes:
      # Monta o diretório atual, com todos os dados do projeto, 
      # dentro do diretório /app
      - ./front-end:/app
    # Lista de serviços do qual este serviço depende
    depends_on:
      # Precisa do banco funcionando antes de subir o node
      - backend
    # Lista de portas mapeadas de dentro para fora do container
    # na notação porta_de_fora:porta_de_dentro
    ports:
      # Expõe a porta padrão da aplicação: altere aqui caso use outra porta
      - 3000:3000
    # Configura as variáveis de ambiente dentro do container
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      JWT_SECRET: secret


  # Serviço que irá rodar o banco de dados
  db:
    # Caso esteja utilizando MacOS M1, descomentar a linha abaixo
    # platform: linux/x86_64
    # Se a linha de cima não resolver, esta abaixo é outra opção
    # platform: linux/arm64/v8
    container_name: app_delivery_db
    image: mysql:8.0.21
    restart: always
    # Lista de portas mapeadas de dentro para fora do container
    # na notação porta_de_fora:porta_de_dentro
    ports:
      # Expõe a porta padrão do banco de dados
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password

# Lista de redes que os containeres irão utilizar
networks:
  # Rede padrão, criada automaticamente
  default:
    # Dá um nome específico à rede padrão
    name: app_delivery_net
